template = "https://github.com/giellalt/template-lang-und"
rev_id = 324
template_sha = "e348abe50c6a27ca569f7cb967cc9b3a3be7d9f9"

[replacements]
__GLOTTOLOG_ID__ = "soma1255"
__REPO__ = "lang-som"
__UND2C__ = "so"
__UNDEFINED__ = "Somali"
__UND__ = "som"
